### ISSUE TITLE
MQTT-615 Clarification of behaviour at end of virtual connection

### ISSUE THREAD

**Issue by icraggs** [oasis-tcs/mqtt#10]
https://issues.oasis-open.org/browse/MQTT-615

**Comment by icraggs** [comment]
Simon Johnson:

Agreed this term is required. Ian will define this in the terminology section of the document. Virtual connection is a construct that can be used for a drop in replacement for the Connection entity in MQTT 3x & 5x

**Comment by simon622** [comment]
Ian to decorate the operational behaviour section with the semantics of VC

**Comment by icraggs** [comment]
Done. Also tracking in Jira again.
