### ISSUE TITLE
MQTT-606 Add WAKE packet

### ISSUE THREAD

**Issue by icraggs** [oasis-tcs/mqtt#15]
https://issues.oasis-open.org/browse/MQTT-606

It should be possible for the GW to optionally interrupt the sleep of a client when the GW deems it necessary (for example it has a large buffer or important messages to deliver).

The client may not be able to respond or CHOOSE not to respond, in which case all the rules of sleep are maintained.. however if it CAN respond and if it chooses to, it should be able to wake up by responding with a PINGRESP and then awaiting outstanding messages - the rest of the sleep state is governed by the normal rule, ie. GW terminated using a PINGRESP.

Why?  many new cellular technologies provide the capability of waking devices up from various states of sleep or deep sleep (for example WuS 3gpp rev 15). It would be wise to enable the network to attempt to wake devices when it deems fit.

**Comment by icraggs** [comment]
Davide: 

I would propose, in order to be aligned with chapter 4.19, that the client may decide to reply to a PINGREQ with a PINGREQ to the GW. So basically the PINGREQ from the GW is a trigger to indicate to the client that there is something got it buffered.

**Comment by icraggs** [comment]
[Simon Johnson [X] (Inactive)](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=simon622867) added a comment - 04/Jan/24 5:00 PM

    We need to protect against the denial of sleep attack.

Permalink
simon622867[ Simon Johnson [X] (Inactive)](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=simon622867) added a comment - 04/Jan/24 5:01 PM

Need to consider this abstract from NB-IoT - it should be applicable of all networking environments.
Permalink
ian.craggs[ Ian Craggs [X] (Inactive)](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=ian.craggs) added a comment - 08/Jan/24 6:38 PM

I wonder if it's right to use a PINGREQ in this case, given that the response could be nothing, or another PINGREQ, rather than a PINGRESP in the normal case. Should it be a new packet entirely (e.g. WAKEUP)?
Permalink
davide.lenzarini[ Davide Lenzarini [X] (Inactive)](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=davide.lenzarini) added a comment - 09/Jan/24 8:26 AM

[Ian Craggs [X]](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=ian.craggs) I agree a new dedicated WAKEUP packet seems a more elegant solution.
Permalink
ian.craggs[ Ian Craggs [X] (Inactive)](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=ian.craggs) added a comment - 09/Jan/24 10:24 AM

It's not as if we are short of packet types either, given that we're getting rid of 5 or 6 will request/update messages.

People

    Assignee:
        Unassigned 

    Reporter:
        simon622867 Simon Johnson [X] (Inactive) 

    Watchers:
        3 Start watching this issue 

Dates

    Created:
        14/Dec/23 5:29 PM 

    Updated:
        09/Jan/24 10:24 AM

**Comment by icraggs** [comment]
Andy S-C: this is like an MQTT out-of-band shoulder tap. So a wakeup packet would be a good idea.

**Comment by sthagen** [comment]
At https://issues.oasis-open.org/browse/MQTT-606
