### ISSUE TITLE
MQTT-562 Optional features

### ISSUE THREAD

**Issue by icraggs** [oasis-tcs/mqtt#17]
https://issues.oasis-open.org/browse/MQTT-562

There is general consensus that the core part of the specification is required in order to be considered compliant. There will be a caveat for known features that will be clearly marked as optional, of which Discovery will be a candidate.

**Comment by icraggs** [comment]
Ian Craggs [X] (Inactive) added a comment - 06/May/20 12:39 PM

The majority of the standard should be mandatory, or 'Core'.  Any optional features should be in a clearly marked section, Extended or some similar term.

ian.craggs[ Ian Craggs [X] (Inactive)](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=ian.craggs) added a comment - 11/May/20 12:34 PM

The only candidate feature for the 'extended' section at the moment is discover.

ian.craggs[ Ian Craggs [X] (Inactive)](https://issues.oasis-open.org/secure/ViewProfile.jspa?name=ian.craggs) added a comment - 05/Oct/23 3:45 PM

Simon suggests that protection and discovery are two big enough subjects to describe as optional and to be called out in the specification

**Comment by icraggs** [comment]
Tracking in Jira again.

**Comment by sthagen** [comment]
At https://issues.oasis-open.org/browse/MQTT-562
